stages:
  - build
  - deploy

variables:
  APP_NAME: $APP_NAME

build:
  image: docker:latest
  stage: build

  only:
    - dev

  before_script:
    - echo "🔧 Configuring Docker..."
    - |
      if [ -n "$IP_ADDRESS_REGISTRY" ]; then
        echo "$IP_ADDRESS_REGISTRY $DOCKER_REGISTRY" >> /etc/hosts
      fi
    - echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
    - touch .env

  script:
    - echo "🚀 Deploying to Docker..."
    - |
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
       export APP_NAME="${APP_NAME_PROD}"
       export DOMAIN_NAME="${DOMAIN_NAME_PROD}"
       printf "%s\n" "$PROD_ENV" > .env
      else
       export APP_NAME="${APP_NAME_STAGING}"
       export DOMAIN_NAME="${DOMAIN_NAME_STAGING}"
       printf "%s\n" "$STAGING_ENV" > .env
      fi 
    - export $(grep -v '^\s*#' .env | sed '/^\s*$/d' | sed 's/ *= */=/' | xargs)
    - docker info
    - docker build -t $DOCKER_REGISTRY/$REGISTRY_PROJECT/$APP_NAME:$DOCKER_TAG .
    - echo "📤 Pushing Docker images..."
    - docker push $DOCKER_REGISTRY/$REGISTRY_PROJECT/$APP_NAME:$DOCKER_TAG

deploy:

  image: docker:latest
  stage: deploy

  only:
    - dev

  before_script:
    - echo "🔧 Configuring Kubernetes..."
    - apk update && apk add --no-cache curl gettext
    - curl -LO $KUBECTL_URL
    - chmod +x kubectl && mv ./kubectl /usr/local/bin/kubectl
    - mkdir -p .kube
    - touch .kube/config
    - touch .env
    - cp "$KUBE_CONFIG" .kube/config

  script:
    - echo "🚀 Deploying to Kubernetes..."
    - |
      if [ "$CI_COMMIT_REF_NAME" == "main" ]; then
       export APP_NAME="${APP_NAME_PROD}"
       export DOMAIN_NAME="${DOMAIN_NAME_PROD}"
       printf "%s\n" "$PROD_ENV" > .env
      else
       export APP_NAME="${APP_NAME_STAGING}"
       export DOMAIN_NAME="${DOMAIN_NAME_STAGING}"
       printf "%s\n" "$STAGING_ENV" > .env
      fi
    - export $(grep -v '^\s*#' .env | sed '/^\s*$/d' | sed 's/ *= */=/' | xargs)
    - kubectl --kubeconfig .kube/config delete deployment --ignore-not-found $APP_NAME -n itfasilkom 
    - kubectl --kubeconfig .kube/config delete secret --ignore-not-found $APP_NAME-secret -n itfasilkom
    - kubectl --kubeconfig .kube/config create secret generic $APP_NAME-secret --from-env-file=.env --dry-run=client -o yaml > $APP_NAME-secret.yaml
    - kubectl --kubeconfig .kube/config apply -f $APP_NAME-secret.yaml -n itfasilkom
    
    # Deploy Redis into pods
    - echo "🚀 Deploying Redis..."
    - envsubst < "deployment-redis.yaml" | kubectl --kubeconfig .kube/config apply -n itfasilkom -f -
    
    # Deploy App into Pods
    - echo "🚀 Deploying App..."
    - envsubst < "deployment-${APP_NAME}.yaml" | kubectl --kubeconfig .kube/config apply -n itfasilkom -f -

  dependencies:
    - build