apiVersion: v1
kind: Service
metadata:
  name: kowl-dev-redesign-be-redis
  namespace: itfasilkom
spec:
  ports:
    - port: 6379
  selector:
    app: kowl-dev-redesign-be-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kowl-dev-redesign-be-redis
  namespace: itfasilkom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kowl-dev-redesign-be-redis
  template:
    metadata:
      labels:
        app: kowl-dev-redesign-be-redis
    spec:
      containers:
        - name: kowl-dev-redesign-be-redis
          image: redis:6
          ports:
            - containerPort: 6379
