[supervisord]
nodaemon=true
logfile=/usr/src/app/app_logs/supervisord.log
pidfile=/var/run/supervisord.pid

[program:uvicorn]
command=uvicorn kwl.asgi:application --host 0.0.0.0 --port 8042
directory=/usr/src/app
autostart=true
autorestart=true
stdout_logfile=/usr/src/app/app_logs/uvicorn.log
stderr_logfile=/usr/src/app/app_logs/uvicorn_error.log
priority=1

[program:celery_worker]
command=celery -A kwl worker --loglevel=info
directory=/usr/src/app
autostart=true
autorestart=true
stdout_logfile=/usr/src/app/app_logs/celery_worker.log
stderr_logfile=/usr/src/app/app_logs/celery_worker_error.log
priority=2
stopwaitsecs=600
killasgroup=true
stopasgroup=true

[program:celery_beat]
command=celery -A kwl beat --loglevel=info
directory=/usr/src/app
autostart=true
autorestart=true
stdout_logfile=/usr/src/app/app_logs/celery_beat.log
stderr_logfile=/usr/src/app/app_logs/celery_beat_error.log
priority=3