# Generated by Django 5.0.2 on 2024-04-08 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('color_theme', models.CharField(choices=[('blue', 'blue'), ('tosca', 'tosca'), ('orange', 'orange'), ('pink', 'pink'), ('yellow', 'yellow')], max_length=6)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assistant_team', models.ManyToManyField(blank=True, related_name='assistants', to='authentication.student')),
                ('lecturer_team', models.ManyToManyField(blank=True, related_name='lecturer', to='authentication.lecturer')),
                ('students', models.ManyToManyField(blank=True, related_name='students', to='authentication.student')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('goals', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
