# Generated by Django 5.0.2 on 2024-04-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
