# Generated by Django 5.0.2 on 2024-05-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_kwluser_domisili'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewarditem',
            name='detail_instruction',
            field=models.CharField(default='ada', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='expired_date',
            field=models.DateTimeField(default='2024-05-01 12:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewarditem',
            name='stock',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='RewardStudentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_point', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.DeleteModel(
            name='RewardPoint',
        ),
    ]
