# Generated by Django 5.0.2 on 2024-05-02 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rewarditem_detail_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarditem',
            name='expired_date',
            field=models.CharField(max_length=30),
        ),
    ]
