# Generated by Django 5.0.2 on 2024-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_course_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='goals',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
