# Generated by Django 5.0.2 on 2024-05-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_rewarditem_expired_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarditem',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rewarditem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rewardstudentpoint',
            name='total_point',
            field=models.IntegerField(default=0),
        ),
    ]
