# Generated by Django 5.0.2 on 2024-04-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=15),
        ),
    ]
