# Generated by Django 5.0.2 on 2024-05-09 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_role'),
        ('course', '0005_remove_course_assistant_team_feedback_kwlpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwlpoint',
            name='kwl_status',
            field=models.CharField(choices=[('know', 'know'), ('wtk', 'wtk'), ('learned', 'learned')], default='know', max_length=10),
        ),
        migrations.CreateModel(
            name='LastAccessedStudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_accessed', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
