# Generated by Django 5.0.2 on 2024-04-21 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_term_alter_course_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
    ]
