# Generated by Django 5.0.2 on 2024-05-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_kwlpoint_kwl_status_lastaccessedstudentcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
    ]
