# Generated by Django 5.0.2 on 2024-05-10 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_role'),
        ('course', '0007_alter_course_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedeemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('reward_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.rewarditem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
