# Generated by Django 5.0.2 on 2024-05-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_redeemhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwlpoint',
            name='know_score',
        ),
        migrations.RemoveField(
            model_name='kwlpoint',
            name='learned_score',
        ),
        migrations.RemoveField(
            model_name='kwlpoint',
            name='wtk_score',
        ),
    ]
