# Generated by Django 5.0.2 on 2024-05-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_role'),
        ('course', '0009_remove_kwlpoint_know_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kwlpoint',
            name='know_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kwlpoint',
            name='learned_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kwlpoint',
            name='wtk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PinnedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
