# Generated by Django 5.0.2 on 2024-06-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_kwlpoint_know_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kwlpoint',
            name='know_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kwlpoint',
            name='learned_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kwlpoint',
            name='wtk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='LastAccessedStudentCourse',
        ),
    ]
