# Generated by Django 5.0.2 on 2024-05-13 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_role'),
        ('course', '0010_course_updated_kwlpoint_know_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerPinnedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.lecturer')),
                ('pinned_course', models.ManyToManyField(blank=True, related_name='lecturer_pinned_course', to='course.course')),
            ],
        ),
        migrations.DeleteModel(
            name='PinnedCourse',
        ),
    ]
