# Generated by Django 5.0.2 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_alter_feedback_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewarditem',
            name='detail_instruction',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(),
        ),
    ]
