# Generated by Django 5.0.2 on 2024-07-06 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_alter_rewarditem_detail_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_name',
            field=models.CharField(max_length=100),
        ),
    ]
