# Generated by Django 5.0.2 on 2025-07-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_full_name_alter_course_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
