# Generated by Django 5.0.2 on 2025-07-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_topic_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
