# Generated by Django 5.0.2 on 2025-07-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_course_enrollment_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='close_time',
            field=models.DateTimeField(blank=True, help_text='Waktu topic ditutup untuk akses', null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='open_time',
            field=models.DateTimeField(blank=True, help_text='Waktu topic dibuka untuk akses', null=True),
        ),
    ]
