# Generated by Django 5.0.2 on 2025-07-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_topic_close_time_topic_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='enable_close_time',
            field=models.BooleanField(default=False, help_text='Aktifkan pembatasan waktu tutup'),
        ),
        migrations.AddField(
            model_name='topic',
            name='enable_open_time',
            field=models.BooleanField(default=False, help_text='Aktifkan pembatasan waktu buka'),
        ),
    ]
