# Generated by Django 5.0.2 on 2025-09-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_studentactivity_activestudentsession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActiveStudentSession',
        ),
    ]
