# Generated by Django 5.0.2 on 2025-11-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_delete_activestudentsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
