# Generated by Django 5.0.2 on 2025-11-17 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_course_is_archived_topic_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='learning_objective',
            field=models.TextField(blank=True, null=True),
        ),
    ]
