# Generated by Django 5.0.2 on 2026-02-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_topic_learning_objective'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='institusi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prodi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
