# Generated by Django 5.0.2 on 2025-10-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestquizattempt',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
