# Generated by Django 5.0.2 on 2025-10-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_kwluser_google_id'),
        ('quiz', '0002_alter_guestquizattempt_guest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquizanswer',
            name='guest_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.guestquizattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquizanswer',
            unique_together={('guest_attempt', 'question'), ('student', 'question')},
        ),
    ]
