# Generated by Django 5.0.2 on 2025-10-22 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_studentquizanswer_guest_attempt_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentquizanswer',
            unique_together=set(),
        ),
        # Hapus field student lama (bigint)
        migrations.RemoveField(
            model_name='studentquizanswer',
            name='student',
        ),
        # Rename guest_attempt menjadi student (UUID)
        migrations.RenameField(
            model_name='studentquizanswer',
            old_name='guest_attempt',
            new_name='student',
        ),
    ]
