# Generated by Django 5.0.2 on 2025-10-22 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_studentquizanswer_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquizanswer',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.guestquizattempt'),
        ),
        migrations.AlterUniqueTogether(
            name='studentquizanswer',
            unique_together={('student', 'question')},
        ),
    ]
