"""
Django settings for kwl project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file


load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'mediafiles')
MEDIA_URL = '/media/'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
if os.getenv('DEBUG') == 'True':
    DEBUG = True
else:
    DEBUG = False


ALLOWED_HOSTS = [
    host for host in [
        os.getenv("FRONTEND_URL"),
        os.getenv("BACKEND_URL"),
    ] if host is not None
] + ['localhost', '127.0.0.1', 'be-kwl-dev.cs.ui.ac.id', ".railway.app",
    ".up.railway.app",]

CSRF_TRUSTED_ORIGINS = [
    f"https://{url.lstrip('https://').lstrip('http://')}" for url in [
        os.getenv("BACKEND_URL"),
        os.getenv("FRONTEND_URL"),
    ] if url is not None
] + ['https://be-kwl-dev.cs.ui.ac.id', 'https://kwl-dev.cs.ui.ac.id']

CORS_ALLOWED_ORIGINS = [
    f"https://{url.lstrip('https://').lstrip('http://').rstrip('/')}" for url in [
        os.getenv("FRONTEND_URL"),
        os.getenv("BACKEND_URL"),
    ] if url is not None
] + [
    "https://kwl-redesign.vercel.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://kwl-dev.cs.ui.ac.id",
    "https://be-kwl-dev.cs.ui.ac.id",
]

# Application definition

SITE_ID = 1


SIGNING_KEY = os.getenv('SIGNING_KEY')
SIMPLE_JWT = {
    "TOKEN_OBTAIN_SERIALIZER": "my_app.serializers.MyTokenObtainPairSerializer",
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=2),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "SIGNING_KEY": SIGNING_KEY,  # generate a key and replace me
    "ALGORITHM": "HS512",
}



# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_USE_TLS = True
# EMAIL_PORT = 587
# EMAIL_HOST_USER = os.getenv('EMAIL_USER')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_PASSWORD')
# EMAIL_USE_SSL = False

EMAIL_PORT=465
EMAIL_USE_SSL=True
EMAIL_HOST=os.environ.get('EMAIL_HOST')
EMAIL_HOST_USER=os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD=os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL=os.environ.get('DEFAULT_FROM_EMAIL')
EMAIL_BACKEND='django.core.mail.backends.smtp.EmailBackend'

AUTH_USER_MODEL = 'authentication.KwlUser'
FRONTEND_URL = os.getenv('FRONTEND_URL')


INSTALLED_APPS = [
    'django_prometheus',
    'authentication',
    'course',
    'know',
    'wtk',
    'learned',
    'analysis',
    'quiz',
    'kuesioner',
    'corsheaders',
    'drf_yasg',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'django.contrib.sites', 
    'django.contrib.admin',
    'django_extensions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    
]

MIDDLEWARE = [
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware'
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],
     'EXCEPTION_HANDLER': 'authentication.utils.custom_exception_handler'
}

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

SWAGGER_SETTINGS = {
    
    'SECURITY_DEFINITIONS': {
        'Bearer':{
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    },

}

ROOT_URLCONF = 'kwl.urls'


GRAPH_MODELS ={
    'all_applications': True,
    'graph_models': True,
     }

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]



WSGI_APPLICATION = 'kwl.wsgi.application'
ASGI_APPLICATION = 'kwl.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/0"],
        },
    },
}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv('DATABASE_NAME', 'test_db'),
        'USER': os.getenv('DATABASE_USER', 'postgres'),
        'PASSWORD': os.getenv('DATABASE_PASSWORD', 'postgres'),
        'HOST': os.getenv('DATABASE_HOST', '127.0.0.1'),
        'PORT': os.getenv('DATABASE_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Whitenoise configuration
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Additional Whitenoise settings
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True



# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# minIO Config
AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT")
AWS_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_SECRET_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_STORAGE_BUCKET_NAME")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'
AWS_QUERYSTRING_AUTH = False
AWS_S3_VERIFY = False
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_S3_USE_SSL = os.getenv("MINIO_SECURE")

# Keycloak Config
KEYCLOAK_REALM = os.getenv('KEYCLOAK_REALM')
KEYCLOAK_SERVER_URL = os.getenv('KEYCLOAK_SERVER_URL')
KEYCLOAK_CERTS_URL = os.getenv('KEYCLOAK_CERTS_URL')
KEYCLOAK_ISSUER_URL = os.getenv('KEYCLOAK_ISSUER_URL')
KEYCLOAK_AUDIENCE = os.getenv('KEYCLOAK_AUDIENCE', 'account')
KEYCLOAK_KEYS_CACHE_TIMEOUT = int(os.getenv('KEYCLOAK_KEYS_CACHE_TIMEOUT', '3600')) 

# Google OAuth2 Config
BASE_APP_URL = os.getenv("BASE_APP_URL")
BASE_API_URL = os.getenv("BASE_API_URL")
GOOGLE_OAUTH2_CLIENT_ID = os.getenv("GOOGLE_OAUTH2_CLIENT_ID")
GOOGLE_OAUTH2_CLIENT_SECRET = os.getenv("GOOGLE_OAUTH2_CLIENT_SECRET")

# Celery Config
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = os.getenv("REDIS_PORT", "6379")
CELERY_BROKER_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'
CELERY_RESULT_BACKEND = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'

# Windows compatibility settings
import platform
if platform.system() == 'Windows':
    # Use solo pool for Windows (single process)
    CELERY_WORKER_POOL = 'solo'
    # Alternative: use threads instead of processes
    # CELERY_WORKER_POOL = 'threads'
    CELERY_WORKER_CONCURRENCY = 1
else:
    # Use default prefork pool for Unix/Linux
    CELERY_WORKER_POOL = 'prefork'
    CELERY_WORKER_CONCURRENCY = 4

# Serialization
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Timezone
CELERY_TIMEZONE = 'Asia/Jakarta'
# Task settings
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 menit max
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # Soft limit 25 menit
# Retry settings
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
# Broker connection settings
CELERY_BROKER_CONNECTION_RETRY = True
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BROKER_CONNECTION_MAX_RETRIES = 10

# Windows-specific optimizations
if platform.system() == 'Windows':
    # Disable result backend for Windows if not needed
    # CELERY_RESULT_BACKEND = None
    # Reduce broker connection pool
    CELERY_BROKER_POOL_LIMIT = 1
    # Optimize for Windows
    CELERY_TASK_ALWAYS_EAGER = False
    CELERY_TASK_EAGER_PROPAGATES = True

# Frontend URL for email templates
FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://kwl-dev.cs.ui.ac.id')