# Generated by Django 5.0.2 on 2025-11-04 16:07

import django.db.models.deletion
import kuesioner.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0016_kwluser_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuesioner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('question_type', models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Polling', 'Polling'), ('Open Ended', 'Open Ended')], max_length=50)),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='private', max_length=50)),
                ('pin', models.IntegerField(default=kuesioner.models.generate_unique_pin, unique=True)),
                ('is_started', models.BooleanField(default=False)),
                ('is_lobby', models.BooleanField(default=False)),
                ('if_finished', models.BooleanField(default=False)),
                ('lecturer_team', models.ManyToManyField(related_name='kuesioners', to='authentication.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='KuesionerSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_participants', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('kuesioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='kuesioner.kuesioner')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.lecturer')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestQuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('kuesioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_attempts', to='kuesioner.kuesioner')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='kuesioner.kuesionersession')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('question_text', models.TextField()),
                ('time_limit', models.IntegerField(default=5)),
                ('score', models.IntegerField(default=0)),
                ('kuesioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='kuesioner.kuesioner')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('choice_text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='kuesioner.question')),
            ],
        ),
        migrations.CreateModel(
            name='GuestQuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('selected_choices', models.ManyToManyField(blank=True, to='kuesioner.choice')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='kuesioner.guestquizattempt')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kuesioner.question')),
            ],
            options={
                'unique_together': {('guest', 'question')},
            },
        ),
    ]
