# Generated by Django 5.0.2 on 2025-11-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuesioner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuesionersession',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='kuesionersession',
            unique_together={('kuesioner', 'session_number')},
        ),
    ]
