# Generated by Django 5.0.2 on 2024-04-23 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtkChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_answer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WantToKnow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('checkbox', 'Checkbox'), ('reflection', 'Reflection')], default='reflection', max_length=255)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
            ],
        ),
        migrations.CreateModel(
            name='Prereading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prereading', models.TextField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='prereading_files/')),
                ('wtk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wanttoknow')),
            ],
        ),
        migrations.CreateModel(
            name='WtkPollQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('choices', models.ManyToManyField(blank=True, related_name='poll_choices', to='wtk.wtkchoices')),
                ('want_to_know', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wanttoknow')),
            ],
        ),
        migrations.CreateModel(
            name='WtkReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('wtk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wanttoknow')),
            ],
        ),
        migrations.CreateModel(
            name='WtkReflectionStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflection', models.TextField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('wtk_ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wtkreflection')),
            ],
        ),
        migrations.CreateModel(
            name='WtkStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('choices', models.ManyToManyField(blank=True, related_name='student_choices', to='wtk.wtkchoices')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('wtk_poll_question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wtkpollquestion')),
            ],
        ),
    ]
