# Generated by Django 5.0.2 on 2024-04-15 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wanttoknow',
            name='total_score',
        ),
    ]
