# Generated by Django 5.0.2 on 2024-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prereading',
            old_name='wtk_id',
            new_name='wtk',
        ),
        migrations.RenameField(
            model_name='wtkpollquestion',
            old_name='want_to_know',
            new_name='wtk',
        ),
        migrations.RenameField(
            model_name='wtkreflection',
            old_name='wtk_id',
            new_name='wtk',
        ),
    ]
