# Generated by Django 5.0.2 on 2024-04-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtkchoices',
            name='wtk_poll_question_id',
        ),
        migrations.AddField(
            model_name='wtkpollquestion',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='poll_choices', to='wtk.wtkchoices'),
        ),
    ]
