# Generated by Django 5.0.2 on 2024-04-22 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0002_remove_wtkchoices_wtk_poll_question_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtkchoices',
            name='alias',
        ),
    ]
