# Generated by Django 5.0.2 on 2024-05-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0002_rename_wtk_id_prereading_wtk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wtkreflectionstudentanswer',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='wtkreflectionstudentanswer',
            old_name='wtk_ref_id',
            new_name='wtk_ref',
        ),
        migrations.RenameField(
            model_name='wtkstudentanswer',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='wtkstudentanswer',
            old_name='wtk_poll_question_id',
            new_name='wtk_poll',
        ),
    ]
