# Generated by Django 5.0.2 on 2024-04-16 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0002_remove_wanttoknow_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtkstudentanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
