# Generated by Django 5.0.2 on 2024-05-04 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_rewarditem_point_alter_rewarditem_stock_and_more'),
        ('wtk', '0003_rename_student_id_wtkreflectionstudentanswer_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prereading',
            name='wtk',
        ),
        migrations.AddField(
            model_name='prereading',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.topic'),
        ),
    ]
