# Generated by Django 5.0.2 on 2024-04-17 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_kwluser_role_id_alter_lecturer_courses_taught'),
        ('wtk', '0003_wtkstudentanswer_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='WtkReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('wtk_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wanttoknow')),
            ],
        ),
        migrations.CreateModel(
            name='WtkReflectionStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflection', models.TextField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('wtk_ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wtkreflection')),
            ],
        ),
    ]
