# Generated by Django 5.0.2 on 2024-05-07 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_delete_role'),
        ('wtk', '0004_remove_prereading_wtk_prereading_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wtkreflectionstudentanswer',
            name='score',
        ),
        migrations.CreateModel(
            name='WtkPollStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.ManyToManyField(blank=True, related_name='student_choices', to='wtk.wtkchoices')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('wtk_poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.wtkpollquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='WtkStudentAnswer',
        ),
    ]
