# Generated by Django 5.0.2 on 2024-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0004_wtkreflection_wtkreflectionstudentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='wtkchoices',
            name='alias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
