# Generated by Django 5.0.2 on 2024-05-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0005_remove_wtkreflectionstudentanswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttoknow',
            name='total_participantws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wtkchoices',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
