# Generated by Django 5.0.2 on 2024-05-08 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0006_wanttoknow_total_participantws_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanttoknow',
            old_name='total_participantws',
            new_name='total_participants',
        ),
    ]
