# Generated by Django 5.0.2 on 2024-05-13 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0007_rename_total_participantws_wanttoknow_total_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanttoknow',
            name='prereading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wtk.prereading'),
        ),
    ]
