# Generated by Django 5.0.2 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0008_wanttoknow_prereading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereading',
            name='prereading',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wtkchoices',
            name='option_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wtkpollquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wtkreflection',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wtkreflectionstudentanswer',
            name='reflection',
            field=models.TextField(),
        ),
    ]
