# Generated by Django 5.0.2 on 2025-07-18 01:01

import utils.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtk', '0009_alter_prereading_prereading_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereading',
            name='file',
            field=models.FileField(blank=True, null=True, storage=utils.custom_storage.MinioMediaStorage(), upload_to='prereading_files/'),
        ),
    ]
