# Generated by Django 5.0.2 on 2024-03-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('course', '0002_topic_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='courses_taught',
            field=models.ManyToManyField(to='course.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='assistant_courses',
            field=models.ManyToManyField(blank=True, related_name='assistants', to='course.course'),
        ),
    ]
