# Generated by Django 5.0.2 on 2024-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_lecturer_courses_taught_student_assistant_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwluser',
            name='role',
            field=models.CharField(default=1, max_length=8, verbose_name={('Admin', 'Admin'), ('Asdos', 'Asdos'), ('Lecturer', 'Lecturer'), ('Student', 'Student')}),
            preserve_default=False,
        ),
    ]
