# Generated by Django 5.0.2 on 2024-04-24 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='lecturer_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
