# Generated by Django 5.0.2 on 2024-04-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwluser',
            name='role_id',
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='courses_taught',
            field=models.ManyToManyField(blank=True, related_name='courses_taughts', to='course.course'),
        ),
    ]
