# Generated by Django 5.0.2 on 2024-04-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_lecturer_lecturer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwluser',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
