# Generated by Django 5.0.2 on 2024-04-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_kwluser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwluser',
            name='domisili',
            field=models.CharField(default='rumah', help_text="User's domicile", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kwluser',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student'), ('assistant', 'Assistant')], default='student', help_text='Token for resetting password', max_length=10),
        ),
    ]
