# Generated by Django 5.0.2 on 2024-04-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_kwluser_domisili_alter_kwluser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwluser',
            name='domisili',
            field=models.CharField(blank=True, help_text="User's domicile", max_length=100, null=True),
        ),
    ]
