# Generated by Django 5.0.2 on 2024-05-02 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_kwluser_domisili'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='courses_taught',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assistant_courses',
        ),
    ]
