# Generated by Django 5.0.2 on 2024-05-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_lecturer_courses_taught_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='kwluser',
            name='reset_password_token',
            field=models.CharField(blank=True, help_text='Token for resetting password', max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='kwluser',
            name='role',
        ),
        migrations.AddField(
            model_name='kwluser',
            name='role',
            field=models.ManyToManyField(null=True, related_name='user_role', to='authentication.role'),
        ),
    ]
