# Generated by Django 5.0.2 on 2024-05-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_role_alter_kwluser_reset_password_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kwluser',
            name='role',
        ),
        migrations.AddField(
            model_name='kwluser',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=10),
        ),
    ]
