# Generated by Django 5.0.2 on 2024-05-06 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_kwluser_role_kwluser_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
