# Generated by Django 5.0.2 on 2024-07-04 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_lecturer_department_alter_lecturer_lecturer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResetPasswordToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='kwluser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="User's profile photo", null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='kwluser',
            name='role',
            field=models.CharField(choices=[('lecturer', 'Lecturer'), ('student', 'Student')], default='student', help_text="User's role", max_length=10),
        ),
        migrations.AlterField(
            model_name='kwluser',
            name='reset_password_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.resetpasswordtoken'),
        ),
    ]
