# Generated by Django 5.0.2 on 2025-07-18 01:01

import utils.custom_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_resetpasswordtoken_alter_kwluser_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwluser',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text="User's profile photo", null=True, storage=utils.custom_storage.MinioMediaStorage(), upload_to='profile_photos/'),
        ),
    ]
