# Generated by Django 5.0.2 on 2025-07-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_kwluser_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kwluser',
            name='role',
            field=models.CharField(blank=True, choices=[('lecturer', 'Lecturer'), ('student', 'Student')], help_text="User's role", max_length=10, null=True),
        ),
    ]
