# Generated by Django 5.0.2 on 2025-07-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_alter_kwluser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwluser',
            name='keycloak_id',
            field=models.CharField(blank=True, help_text='Keycloak ID for the user', max_length=100, null=True, unique=True),
        ),
    ]
