# Generated by Django 5.0.2 on 2025-07-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_kwluser_keycloak_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='kwluser',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google ID for the user', max_length=100, null=True, unique=True),
        ),
    ]
