# Generated by Django 5.0.2 on 2026-02-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_kwluser_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the consent', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the consent', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='kwluser',
            name='consent',
            field=models.ManyToManyField(blank=True, related_name='users', to='authentication.consent'),
        ),
    ]
