# Generated by Django 5.0.2 on 2026-02-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_userconsent_alter_kwluser_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='institusi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='institusi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
