# Generated by Django 5.0.2 on 2024-04-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('reflection', 'Reflection'), ('quiz', 'Quiz')], default='reflection', max_length=255)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='learned_images/')),
                ('learned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learned.learned')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_answer', models.CharField(max_length=255)),
                ('isCorrect', models.BooleanField(default=False)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('learned_quiz_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learned.learnedquizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedQuizStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('learned_quiz_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learned.learnedquizquestion')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('learned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learned.learned')),
            ],
        ),
        migrations.CreateModel(
            name='LearnedReflectionStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflection', models.TextField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
                ('wtk_ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learned.learnedreflection')),
            ],
        ),
    ]
