# Generated by Django 5.0.2 on 2024-04-28 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnedquizstudentanswer',
            name='score',
        ),
        migrations.RemoveField(
            model_name='learnedreflectionstudentanswer',
            name='score',
        ),
    ]
