# Generated by Django 5.0.2 on 2024-04-28 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0002_remove_learnedquizstudentanswer_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnedreflectionstudentanswer',
            old_name='wtk_ref_id',
            new_name='learned',
        ),
    ]
