# Generated by Django 5.0.2 on 2024-05-03 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0003_rename_wtk_ref_id_learnedreflectionstudentanswer_learned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learnedquizoption',
            old_name='learned_quiz_id',
            new_name='learned_quiz',
        ),
        migrations.RenameField(
            model_name='learnedquizstudentanswer',
            old_name='learned_quiz_id',
            new_name='learned_quiz',
        ),
        migrations.RenameField(
            model_name='learnedquizstudentanswer',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='learnedreflectionstudentanswer',
            old_name='learned',
            new_name='learned_ref',
        ),
        migrations.RenameField(
            model_name='learnedreflectionstudentanswer',
            old_name='student_id',
            new_name='student',
        ),
    ]
