# Generated by Django 5.0.2 on 2024-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0004_rename_learned_quiz_id_learnedquizoption_learned_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnedquizstudentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='learnedquizstudentanswer',
            name='learned_quiz',
        ),
        migrations.AddField(
            model_name='learned',
            name='total_participants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='learnedquizstudentanswer',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='student_answers', to='learned.learnedquizoption'),
        ),
    ]
