# Generated by Django 5.0.2 on 2024-05-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0005_remove_learnedquizstudentanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learnedquizquestion',
            name='image',
        ),
    ]
