# Generated by Django 5.0.2 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learned', '0006_remove_learnedquizquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnedquizoption',
            name='option_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learnedquizquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learnedreflection',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='learnedreflectionstudentanswer',
            name='reflection',
            field=models.TextField(),
        ),
    ]
