# Generated by Django 5.0.2 on 2024-04-15 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_remove_kwluser_role_id_alter_lecturer_courses_taught'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Know',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('reflection', 'Reflection'), ('quiz', 'Quiz')], default='reflection', max_length=255)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.topic')),
            ],
        ),
        migrations.CreateModel(
            name='KnowQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='know_images/')),
                ('know', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='know.know')),
            ],
        ),
        migrations.CreateModel(
            name='KnowQuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option_answer', models.CharField(max_length=255)),
                ('isCorrect', models.BooleanField(default=False)),
                ('know_quiz_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='know.knowquizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='KnowQuizStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('know_quiz_question_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='know.knowquizquestion')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
        migrations.CreateModel(
            name='KnowReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
                ('know_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='know.know')),
            ],
        ),
        migrations.CreateModel(
            name='KnowReflectionStudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflection', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('know_ref_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='know.knowreflection')),
                ('students_answer', models.ManyToManyField(blank=True, related_name='know_ref_answers', to='authentication.student')),
            ],
        ),
    ]
