# Generated by Django 5.0.2 on 2024-04-28 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowreflection',
            old_name='know_id',
            new_name='know',
        ),
    ]
