# Generated by Django 5.0.2 on 2024-04-15 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowreflectionstudentanswer',
            old_name='students_answer',
            new_name='student_id',
        ),
    ]
