# Generated by Django 5.0.2 on 2024-04-15 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_kwluser_role_id_alter_lecturer_courses_taught'),
        ('know', '0002_rename_students_answer_knowreflectionstudentanswer_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowreflectionstudentanswer',
            name='student_id',
        ),
        migrations.AddField(
            model_name='knowreflectionstudentanswer',
            name='student_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.student'),
        ),
    ]
