# Generated by Django 5.0.2 on 2024-05-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0002_rename_know_id_knowreflection_know'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowquizstudentanswer',
            old_name='know_quiz_question_id',
            new_name='quiz',
        ),
        migrations.RenameField(
            model_name='knowquizstudentanswer',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='knowreflectionstudentanswer',
            old_name='know_ref_id',
            new_name='know_ref',
        ),
        migrations.RenameField(
            model_name='knowreflectionstudentanswer',
            old_name='student_id',
            new_name='student',
        ),
    ]
