# Generated by Django 5.0.2 on 2024-05-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0003_rename_know_quiz_question_id_knowquizstudentanswer_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowreflectionstudentanswer',
            name='score',
        ),
    ]
