# Generated by Django 5.0.2 on 2024-04-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0003_remove_knowreflectionstudentanswer_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowreflectionstudentanswer',
            name='reflection',
            field=models.TextField(max_length=255),
        ),
    ]
