# Generated by Django 5.0.2 on 2024-05-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0004_remove_knowreflectionstudentanswer_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowquizoption',
            old_name='know_quiz_id',
            new_name='know_quiz',
        ),
        migrations.RenameField(
            model_name='knowquizstudentanswer',
            old_name='quiz',
            new_name='know_quiz',
        ),
    ]
