# Generated by Django 5.0.2 on 2024-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0004_alter_knowreflectionstudentanswer_reflection'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowquizoption',
            name='alias',
            field=models.CharField(blank=True, choices=[('Opsi A', 'Opsi A'), ('Opsi B', 'Opsi B'), ('Opsi C', 'Opsi C'), ('Opsi D', 'Opsi D')], max_length=255, null=True),
        ),
    ]
