# Generated by Django 5.0.2 on 2024-05-03 06:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0005_rename_know_quiz_id_knowquizoption_know_quiz_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowquizstudentanswer',
            name='score',
        ),
        migrations.AddField(
            model_name='knowquizstudentanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='knowquizstudentanswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
