# Generated by Django 5.0.2 on 2024-05-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0006_remove_knowquizstudentanswer_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='know',
            name='total_participants',
            field=models.IntegerField(default=0),
        ),
    ]
