# Generated by Django 5.0.2 on 2024-05-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0007_know_total_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowquizstudentanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='knowquizstudentanswer',
            name='know_quiz',
        ),
        migrations.AddField(
            model_name='knowquizstudentanswer',
            name='answers',
            field=models.ManyToManyField(blank=True, related_name='student_answers', to='know.knowquizoption'),
        ),
    ]
