# Generated by Django 5.0.2 on 2024-05-10 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0008_remove_knowquizstudentanswer_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowquizquestion',
            name='image',
        ),
    ]
