# Generated by Django 5.0.2 on 2024-07-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('know', '0009_remove_knowquizquestion_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowquizoption',
            name='option_answer',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowquizquestion',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowreflection',
            name='question',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='knowreflectionstudentanswer',
            name='reflection',
            field=models.TextField(),
        ),
    ]
